###health
GET http://118.190.166.136:8080/health

###用户注册
POST http://118.190.166.136:8080/api/v1/user/register

{"cmd":"user_register","userID":"eric"}

###注销用户
POST http://118.190.166.136:8080/api/v1/user/unregister

{
    "cmd":"user_unregister",
    "bcuser_id":"eric",
    "bcuser_key":"private"
}

###api/v1/msisdn/subscribe 签约
POST http://118.190.166.136:8080/api/v1/msisdn/subscribe

{
    "cmd":"subscribe",
    "bcuser_id":"bcuser_id",
    "bcuser_key":"bcuser_key",
    "msisdn":"+8613810167617",
    "eki2":"eki2"
}

###解约
POST http://118.190.166.136:8080/api/v1/msisdn/unsubscribe
Content-Type: application/json

{
    "cmd":"user_unregister",
    "bcuser_id":"bcuser_id",
    "bcuser_key":"bcuser_key",
    "msisdn":"+8613810167617",
    "asset_id":"0x0cd88Cf566e1A9a8569f5c1559c64BCc12ca2778"
}

###api/v1/msisdn/state 查询号码签约信息
POST http://118.190.166.136:8080/api/v1/msisdn/state
Content-Type: application/json

{
    "cmd":"msisdn_state",
    "msisdn":"+8613810167617"
}

###api/v1/msisdn/states 查询多号码签约信息
POST http://118.190.166.136:8080/api/v1/msisdn/states
Content-Type: application/json

{
    "cmd":"msisdn_states",
    "msisdn":["+8613810167616","+8613810167617","+8613810167618"]
}

###api/v1/msisdn/history 查询号码签约历史信息
POST http://118.190.166.136:8080/api/v1/msisdn/history
Content-Type: application/json

{
    "cmd":"msisdn_history",
    "msisdn":"+8613810167617"
}

###api/v1/asset/info 查询资产信息
POST http://118.190.166.136:8080/api/v1/asset/info
Content-Type: application/json

{
    "cmd":"asset_info",
    "asset_id":"0x0cd88Cf566e1A9a8569f5c1559c64BCc12ca2778"
}

###/transfer/query 查询
POST http://118.190.166.136:8080/api/v1/transfer/query
Content-Type: application/json

{
    "cmd":"transt_list",
    "tm":0,
    "start":0,
    "max_no":10
}

###/channels/:channel/height 高度
GET http://118.190.166.136:8080/api/v1/channels/mychannel/height
